name: music-app
version: '2.5'
summary: A music application for ubuntu
description: |
  A music application for ubuntu

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode

apps:
  music-app:
    command: desktop-launch $SNAP/bin/music-app
    desktop: usr/share/applications/music-app.desktop
    plugs:
     - home
     - mir
     - mir-libs
     - mpris
     - opengl
     - pulseaudio
     - unity7
     - unity8

plugs:
  mir-libs:
    interface: content
    content: mir0 
    target: mir-libs
    default-provider: mir-libs

  platform:
    interface: content
    content: ubuntu-app-platform1
    target:  ubuntu-app-platform
    default-provider: ubuntu-app-platform

parts:
  music-app:
    plugin: cmake
    source: .
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
    build-packages:
      - cmake
      - intltool
    stage-packages:
      - libgpm2  # otherwise we get errors in the console
      - gstreamer1.0-fluendo-mp3  # to play mp3's
      - gstreamer1.0-plugins-bad  # otherwise we don't get m4a and friends
      - gstreamer1.0-plugins-good  # explicitly include for now
      - gstreamer1.0-pulseaudio  # not in UAP, otherwise we try to use jack-server
    prime:
      - usr/bin/music-app
      - usr/lib/*/libgpm*
      - usr/lib/*/gstreamer-1.0
      - usr/share/applications/music-app.desktop
      - usr/share/content-hub/peers/music-app
      # - usr/share/locale  # for now don't include locale as this doesn't work anyway?
      - usr/share/music-app
      - usr/share/url-dispatcher/urls/music-app.url-dispatcher
      
    after: [desktop-ubuntu-app-platform]

  environment:
    source: snap/
    plugin: dump
    prime:
      - bin
      - mir-libs
      - ubuntu-app-platform
    organize:
      music-app.wrapper: bin/music-app
    after: [music-app]

